projects:
  comedyconnector:
    schemaPath: amplify/backend/api/comedyconnector/build/schema.graphql
    includes:
      - apps/frontend/cc-frontend/src/app/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: apps/frontend/cc-frontend/src/app/graphql/cc-graphql.service.ts
        docsFilePath: apps/frontend/cc-frontend/src/app/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
